apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: faros
  namespace: system
  labels:
    control-plane: faros
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: faros
      controller-tools.k8s.io: "1.0"
  serviceName: faros
  template:
    metadata:
      labels:
        control-plane: faros
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
